### ISSUE TITLE
Typo in the Structures section

### ISSUE THREAD

**Issue by lafita** [ProteinsWebTeam/Pfam#3]
I found a typo in the Structures section of the Pfam website. The last word of the top paragraph says **protein seqence**. See http://pfam.xfam.org/family/PF12245#tabview=tab9

**Comment by aurel-l** [comment]
Thanks, I fixed that on dev (commit https://github.com/ProteinsWebTeam/Pfam/commit/683e287126506b20e3bcf42254fdcec50e70d6f8).
This should go whenever we re-release the website.
